### ISSUE TITLE
how to?

### ISSUE THREAD

**Issue by zajaklis** [PiotrSperka/ESP8266-WebRadio#1]
can you please describe hardware necessary for webplayer.
i already have VS1053 and im not sure which esp8266 is needed for this setup and how wiring is done.
any help?

at the moment i tryed to compile and flash esp8266-01, but for some reason it does not connect to my wifi.
I already changed
sprintf(config->ssid, "myssid");
    sprintf(config->password, "mypass");

**Comment by PiotrSperka** [comment]
I'm going to publish schematic in next few days. I'm using ESP-07 module. Player in current version uses only ESP8266, VS1053 and FT232 for UART<->USB translation (programming and debugging). Wiring is done as follows:
VS1053 ------> ESP8266
MISO --------> GPIO12
MOSI --------> GPIO13
SCK ----------> GPIO14
XRST --------> GPIO0
DREQ -------> GPIO5
XCS ---------> GPIO15
XDCS -------> GPIO4

**Comment by PiotrSperka** [comment]
After powering up device it should connect to preprogrammed wifi. Then you can open admin panel through web browser (device IP is printed through UART when connection is successful). Moreover, if you want, you can use some UART commands (followed by ENTER key):
wifi.status - connection information
wifi.discon - disconnect wifi
wifi.con("ssid","pass") - connect to wifi
wifi.list - list available wifi networks
cli.start - start playing shoutcast
cli.stop - stop playing shoutcast
cli.port(port_no)
cli.path("path/to/file")
cli.url("some.radio.com")
