### ISSUE TITLE
Using with NodeMCU?

### ISSUE THREAD

**Issue by confile** [PiotrSperka/ESP8266-WebRadio#2]
Can I use this with NodeMCU firmware?

**Comment by PiotrSperka** [comment]
No, you must use this firmware instead of NodeMCU.

**Comment by confile** [comment]
My question is more the following. Do you see It possible to build such a web radio with NodeMCU? Are there cheaper MP3 decoder?

**Comment by PiotrSperka** [comment]
I am pretty sure that there will be problem with small amount of RAM. NodeMCU is for rather small projects, and this project requires a lot of RAM for buffers, etc. The VS10xx are the only MP3 decoders I know.
