### ISSUE TITLE
How to wire ESP8266 to VS1053?

### ISSUE THREAD

**Issue by confile** [PiotrSperka/ESP8266-WebRadio#5]
Could you please publish a wire table how to connect ESP8266 to VS1053?

**Comment by PiotrSperka** [comment]
VS1053 ------> ESP8266
MISO --------> GPIO12
MOSI --------> GPIO13
SCK ----------> GPIO14
XRST --------> GPIO0
DREQ -------> GPIO4
XCS ---------> GPIO15
XDCS -------> GPIO5
